# Generated by Django 5.0.14 on 2025-12-10 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Colegiatura (CMP/CNP)')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía Profesional')),
                ('specialties', models.JSONField(blank=True, default=list, verbose_name='Especialidades')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
