# Generated by Django 5.0.14 on 2025-12-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_organization_user_cognito_sub_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Logo URL'),
        ),
    ]
