# Generated by Django 5.0.14 on 2025-12-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Admin'), ('ORG_OWNER', 'Dueño de Clínica'), ('PROFESSIONAL', 'Nutricionista'), ('PACIENTE', 'Paciente')], default='PROFESSIONAL', max_length=20),
        ),
    ]
