# Generated by Django 5.0.14 on 2025-12-20 03:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin Suscripción'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Inicio Suscripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre del Consultorio/Clínica'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='plan_type',
            field=models.CharField(choices=[('STUDENT', 'Plan Estudiante (Gratis 6 meses)'), ('BASE', 'Plan Base (S/40)'), ('PLUS', 'Plan Plus (S/65)'), ('ELITE', 'Plan Elite (S/119)'), ('ENTERPRISE', 'Plan Clínica (Multi-Nutri)')], default='BASE', max_length=20),
        ),
    ]
