# Generated by Django 5.0.14 on 2025-12-10 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('category', models.CharField(choices=[('PROTEIN', 'Proteína'), ('CARB', 'Carbohidrato'), ('FAT', 'Grasa'), ('VEGETABLE', 'Vegetal'), ('FRUIT', 'Fruta'), ('DAIRY', 'Lácteo'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Kcal (por 100g)')),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Proteínas (g)')),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Carbohidratos (g)')),
                ('fats', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Grasas (g)')),
                ('fiber', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Fibra (g)')),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Plan (Ej: Hipertrofia Fase 1)')),
                ('description', models.TextField(blank=True, verbose_name='Objetivo / Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Es el plan actual?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PACIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(limit_choices_to={'role': 'NUTRICIONISTA'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Plato')),
                ('description', models.TextField(blank=True, verbose_name='Instrucciones / Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_grams', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cantidad (gramos)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='nutrition.meal')),
            ],
            options={
                'verbose_name': 'Ingrediente de Receta',
                'verbose_name_plural': 'Ingredientes de Receta',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(through='nutrition.MealItem', to='nutrition.ingredient'),
        ),
        migrations.CreateModel(
            name='PlanAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día')),
                ('meal_time', models.CharField(choices=[('BREAKFAST', 'Desayuno'), ('MORNING_SNACK', 'Media Mañana'), ('LUNCH', 'Almuerzo'), ('AFTERNOON_SNACK', 'Media Tarde'), ('DINNER', 'Cena')], max_length=20, verbose_name='Momento del día')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.meal', verbose_name='Plato / Receta')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='nutrition.dietplan')),
            ],
            options={
                'verbose_name': 'Comida Asignada',
                'verbose_name_plural': 'Comidas Asignadas',
                'ordering': ['day_of_week', 'meal_time'],
            },
        ),
    ]
