# Generated by Django 5.0.14 on 2025-12-19 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('users', '0004_organization_user_cognito_sub_user_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalpatient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Expediente de Paciente', 'verbose_name_plural': 'Expedientes de Pacientes'},
        ),
        migrations.AddField(
            model_name='clinicalpatient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='clinicalpatient',
            name='app_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_records', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de App Vinculado'),
        ),
        migrations.AlterField(
            model_name='clinicalpatient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Paciente'),
        ),
        migrations.AlterField(
            model_name='clinicalpatient',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clinicalpatient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AlterField(
            model_name='clinicalpatient',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='clinicalpatient',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='users.organization', verbose_name='Clínica'),
        ),
        migrations.AlterField(
            model_name='clinicalpatient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
